apiVersion: v1
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPW1pbmlvCmF3c19zZWNyZXRfYWNjZXNzX2tleT1taW5pbzEyMwo=
kind: Secret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
type: Opaque