apiVersion: v1
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: "oadp"
      endpoint: "minio:9000"
      insecure: true
      access_key: "minio"
      secret_key: "minio123"
kind: Secret
metadata:
  name: oadp-object-storage
type: Opaque
